# Site settings

title: Estado Lógico 2011 Website
email: manu@estadologico.com
description: This is a old site for Estado Lógico
baseurl: "" # e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: unavezfui
github_username:  manumorante

# Build settings
markdown: kramdown